version: '3.8'
services:

  db:
    ports:
      - "6666:5432"

  migration:
    environment:
      - DATABASE_URL=postgresql://app:123qwe@localhost:6666/notifications

  notifications_api:
    environment:
      - NOTIFICATIONS_SENDER_AMQP_URL=amqp://user:pass@rabbitmq:5672/test
    ports:
      - "8001:8001"

  consumers:
    environment:
      - NOTIFICATIONS_ENRICHER_CONSUMER_AMQP_URL=amqp://user:pass@rabbitmq:5672/test

#  redis:
#    ports:
#      - '6379:6379'

#  admin_panel:
#    ports:
#      - "8000:8000"

  rabbitmq:
    ports:
      - "8020:15672"
      - "8030:5672"

#  e2e-tests:
#     image: fastapi-image
#     entrypoint: >
#       sh -c "pytest tests/src/e2e"
#     env_file:
#       - ./.env
#     depends_on:
#       - fastapi