version: '3.8'
services:

  notifications_db:
    ports:
      - "6666:5432"

  fastapi:
    image: fastapi-image
    extends:
      file: docker-compose-base.yml
      service: fastapi
    ports:
      - "8000:8000"

#  e2e-tests:
#     image: fastapi-image
#     entrypoint: >
#       sh -c "pytest tests/src/e2e"
#     env_file:
#       - ./.env
#     depends_on:
#       - fastapi
