version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    env_file:
      - ./.env
    expose:
      - "${POSTGRES_PORT}"
    networks:
      - custom
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migration:
    build:
      context: ./.
      dockerfile: notifications_db/Dockerfile
    environment:
      - DATABASE_URL=postgresql://app:123qwe@db:5432/notifications
    command: bash -c "yoyo apply --database ${DATABASE_URL} /notifications_db/migrations -b"
    depends_on:
      - "db"
    networks:
      - custom

  notifications_api:
    build:
      context: ./.
      dockerfile: notifications_api/Dockerfile
    env_file:
      - ./.env
    networks:
      - custom

volumes:
    pgdata:

networks:
  custom:
    driver: bridge