version: '3.8'
services:

  db:
    ports:
      - "6666:5432"

  migration:
    environment:
      - DATABASE_URL=postgresql://app:123qwe@localhost:6666/notifications

  notifications_api:
    environment:
      - NOTIFICATIONS_SENDER_AMQP_URL=amqp://user:pass@rabbitmq:5672/test
    ports:
      - "8001:8001"

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_VHOST: test
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "8020:15672"
      - "8030:5672"
    networks:
      - custom

#  e2e-tests:
#     image: fastapi-image
#     entrypoint: >
#       sh -c "pytest tests/src/e2e"
#     env_file:
#       - ./.env
#     depends_on:
#       - fastapi
