version: '3.8'
services:

  db:
    ports:
      - "6666:5432"

  notifications_api:
    ports:
      - "8001:8001"

#  e2e-tests:
#     image: fastapi-image
#     entrypoint: >
#       sh -c "pytest tests/src/e2e"
#     env_file:
#       - ./.env
#     depends_on:
#       - fastapi
